config/routes.rb
Rails.application.routes.draw do

  devise_for :students
  devise_for :teachers
  get "student/lessons/basics_angles"

  root to: "home#index"


  namespace :teachers do
    resources :courses
    resources :skills
    resources :lessons
    resources :questions
    resources :answers
    resources :profiles, only: [:show]
  end


  namespace :students do
    resources :profiles, only: [:show]
    resources :courses, only: [:index, :show] do
      resources :skills, only: [:index, :show]
      resources :lessons, only: [:basics_angles]
    end
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :lessons
  belongs_to :course
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/students/skills_controller.rb
class Students::SkillsController < ApplicationController
  before_action :authenticate_student!

	def index
		course = Course.find params[:course_id]
		@skills = course.skills
	end
end

app/controllers/teachers/answers_controller.rb
class Teachers::AnswersController < ApplicationController
  before_action :authenticate_teacher!
end

app/controllers/teachers/courses_controller.rb
class Teachers::CoursesController < ApplicationController
  before_action :authenticate_teacher!
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new course_params
    if @course.save
      redirect_to teachers_courses_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @course.update course_params
      redirect_to @course
    else
      render :edit
    end
  end

  def destroy
    @course.destroy
    redirect_to teachers_courses_path
  end

  private
  def set_course
    @course = Course.find params[:id]
  end

  def course_params
    params.require(:course).permit(
      :name, :code
    )
  end
end

app/controllers/teachers/lessons_controller.rb
class Teachers::LessonsController < ApplicationController
  before_action :authenticate_teacher!
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  def index
    @lessons = Lesson.all
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new lesson_params
    if @lesson.save
      redirect_to teachers_lesson_path @lesson
    else
      render :new
    end
  end

  def show
  end


  def edit
  end

  def update
    if @lesson.update lesson_params
      redirect_to teachers_lesson_path @lesson
    else
      render :edit
    end
  end

  def destroy
    @lesson.destroy
    redirect_to teachers_lessons_path
  end

  private

  def set_lesson
    @lesson = Lesson.find params[:id]
  end

  def lesson_params
    params.require(:lesson).permit(:name, :skill_id, :description)
  end
end

app/controllers/teachers/profiles_controller.rb
class Teachers::ProfilesController < ApplicationController
	def show
	end

	def edit
	end

	def update
	end
end

app/controllers/teachers/questions_controller.rb
class Teachers::QuestionsController < ApplicationController
  before_action :authenticate_teacher!
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new question_params
    if @question.save
      redirect_to teachers_question_path @question
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @question.update question_params
      redirect_to teachers_question_path @question
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to teachers_questions_path
  end

  private

  def set_question
    @question = Question.find params[:id]
  end

  def question_params
    params.require(:question).permit(:name, :lesson_id,)
  end
end

app/controllers/teachers/skills_controller.rb
class Teachers::SkillsController < ApplicationController
  before_action :authenticate_teacher!
  before_action :set_skill, only: [:show, :edit, :update, :destroy]

  def index
    if params[:course_id]
      @course = current_user.courses.find params[:course_id]
      @skills = @course.skills
    else
      @skills = Skill.all
    end
  end

  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new skill_params
    if @skill.save
      redirect_to teachers_skill_path @skill
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @skill.update skill_params
      redirect_to teachers_skill_path @skill
    else
      render :edit
    end
  end

  def destroy
    @skill.destroy
    redirect_to teachers_skills_path
  end

  private

  def set_skill
    @skill = Skill.find params[:id]
  end

  def skill_params
    params.require(:skill).permit(:name, :course_id)
  end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/teachers/skills/_form.html.erb
<% if @skill.errors.any? %>
  <% @skill.errors.full_messages.each do |m| %>
    <p><%= m %></p>
  <% end %>
<% end %>
<%= simple_form_for [:teachers, @skill] do |f| %>
  <%= f.input :name %>
  <%= f.association :course %>


  <%= link_to 'Cancel', teachers_skills_path, class: 'btn btn-default' %>
  <%= f.submit nil, class: 'btn btn-primary' %>
<% end %>

app/views/teachers/skills/edit.html.erb
<%= render partial: 'form' %>

app/views/teachers/skills/index.html.erb
<div class="btn-group btn-group-justified">
  <%= link_to 'New Skill', new_teachers_skill_path, class: 'btn btn-info' %>
</div>

<br>
<br>

<table class="table">
  <thead>
    <th>Name</th>
    <th>Nº Lessons</th>
    <th>Course</th>
    <th><span class="glyphicon glyphicon-pencil"></span></th>
    <th><span class="glyphicon glyphicon-trash" ></span></th>
  </thead>
  <tbody>
    <% @skills.each do |s| %>
      <tr>
        <td><%= link_to s.name, teachers_skill_path(s) %></td>
        <td></td>
        <td><%= s.course.name %></td>
        <td>
          <%= link_to 'Edit', edit_teachers_skill_path(s), class: 'btn btn-default' %>
        </td>
        <td>
          <%= link_to 'X', teachers_skill_path(s), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      <% end %>
  </tbody>
</table>

app/views/teachers/skills/new.html.erb
<%= render partial: 'form' %>

app/views/teachers/skills/show.html.erb
<button type="button" class="btn btn-default">
  <span class="glyphicon glyphicon-plus"></span>
  <%= link_to ' Add New Skill', new_teachers_skill_path%>
</button>

<hr>
<br>

<div class="row">
  <div class="col-md-6">
    <label for="">Name</label>
    <%= @skill.name %>
  </div>
  <div class="col-md-6">
    <label for="">Course</label>
    <%= @skill.course.name %>
  </div>
</div>

<hr>

<button type="button" class="btn btn-default">
  <span class="glyphicon glyphicon-chevron-left"></span>
  <%= link_to ' Back', teachers_skills_path %>
</button>
<button type="button" class="btn btn-default">
  <span class="glyphicon glyphicon-pencil"></span>
  <%= link_to ' Edit', edit_teachers_skill_path %>
</button>