config/routes.rb
Rails.application.routes.draw do

  devise_for :students
  devise_for :teachers
  get "student/lessons/basics_angles"

  root to: "home#index"


  namespace :teachers do
    resources :courses
    resources :skills
    resources :lessons
    resources :questions
    resources :answers
    resources :profiles, only: [:show]
  end


  namespace :students do
    resources :profiles, only: [:show]
    resources :courses, only: [:index, :show] do
      resources :skills, only: [:index, :show]
      resources :lessons, only: [:basics_angles]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :manage, :all
    # if user.has_role? :admin
    #   can :manage, :all
    # elsif user.has_role? :teacher
    #   can :manage, Course
    #   can :manage, Skill
    #   can :manage, Lesson
    #   can :manage, Question
    #   #can :manage, Answer
    # elsif user.has_role? :student 
    #   can :read, :all
    #   can :dashboard, Student
    # end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :skills

    has_many :student_courses, inverse_of: :course
    has_many :students, through: :student_courses, inverse_of: :courses
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :questions
  belongs_to :skill

  def complete_name
  	"#{self.skill.course.name} #{self.skill.name} #{self.name}"
  end
end

app/models/question.rb
class Question < ApplicationRecord
has_many :anwers
belongs_to :lesson
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :lessons
  belongs_to :course
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :student_courses, inverse_of: :student
  has_many :courses, through: :student_courses, inverse_of: :students
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
	belongs_to :student, inverse_of: :student_courses
	belongs_to :course, inverse_of: :student_courses
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    if current_teacher
      redirect_to root_url, :alert => exception.message
    else
      redirect_to students_courses_path
    end
  end

  protected

  def after_sign_in_path_for(resource)
    return students_courses_path if resource.is_a? Student
    request.env['omniauth.origin'] || stored_location_for(resource) || root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/_student_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Números | Ateneo Victoria</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to current_student.email, students_profile_path(current_student) %>
        </li>
        <li class="dropdown">
          <%= link_to('Salir', destroy_student_session_path) %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_teacher_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Courses', teachers_courses_path, class: 'btn btn-link' %>
        </li>

        <li>
          <%= link_to 'Skills', teachers_skills_path, class: 'btn btn-link' %>
        </li>

        <li>
          <%= link_to 'Lessons', teachers_lessons_path, class: 'btn btn-link' %>
        </li>

        <li>
          <%= link_to 'Questions', teachers_questions_path, class: 'btn btn-link' %>
        </li>

        <li>
          <%= link_to 'Answers', teachers_answers_path, class: 'btn btn-link' %>
        </li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to current_teacher.email, teachers_profile_path(current_teacher) %>
        </li>
        <li class="dropdown">
          <%= link_to('Salir', destroy_teacher_session_path) %>
        </li>
      </ul>
      </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Numx</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>

    <% if teacher_signed_in? %>
      <%= render "layouts/teacher_navbar" %>
    <% elsif student_signed_in? %>
      <%= render "layouts/student_navbar" %>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>